
CREATE SEQUENCE IF NOT EXISTS SEQ_ID
START WITH  100
INCREMENT BY 1
CYCLE
NO CACHE;

DROP TABLE IF EXISTS USER;
CREATE TABLE USER(
   ID INT PRIMARY KEY,
   NICKNAME VARCHAR(20),
   PASSWORD VARCHAR(20),
   AGE TINYINT,
   GENDER ENUM('MALE', 'FEMALE')
);
DROP TABLE IF EXISTS ORDER;
CREATE TABLE ORDER(
   ID INT PRIMARY KEY,
   ID_USER INT,
   CREATE_DT TIMESTAMP,
   FOREIGN KEY (ID_USER) REFERENCES USER(ID)
);


